// <auto-generated />
using Boodschap.Features.ShoppingLists.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boodschap.Features.ShoppingLists.Infrastructure.Persistence.Migrations
{
	[DbContext(typeof(BoodschapDbContext))]
	partial class BoodschapDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

			modelBuilder.Entity("Boodschap.Features.ShoppingLists.Domain.ShoppingList", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<bool>("Archived")
						.HasColumnType("INTEGER");

					b.Property<string>("Description")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("TEXT");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("TEXT");

					b.Property<int>("SortOrder")
						.HasColumnType("INTEGER");

					b.HasKey("Id");

					b.ToTable("ShoppingLists");
				});

			modelBuilder.Entity("Boodschap.Features.ShoppingLists.Domain.ShoppingListItem", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<bool>("IsDone")
						.HasColumnType("INTEGER");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("TEXT");

					b.Property<int>("ShoppingListId")
						.HasColumnType("INTEGER");

					b.Property<int>("SortOrder")
						.HasColumnType("INTEGER");

					b.HasKey("Id");

					b.HasIndex("ShoppingListId");

					b.ToTable("ShoppingListItems");
				});

			modelBuilder.Entity("Boodschap.Features.ShoppingLists.Domain.ShoppingListItem", b =>
				{
					b.HasOne("Boodschap.Features.ShoppingLists.Domain.ShoppingList", "ShoppingList")
						.WithMany("Items")
						.HasForeignKey("ShoppingListId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("ShoppingList");
				});

			modelBuilder.Entity("Boodschap.Features.ShoppingLists.Domain.ShoppingList", b =>
				{
					b.Navigation("Items");
				});
#pragma warning restore 612, 618
		}
	}
}