// <auto-generated />
using Boodschap.Features.Authentication.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boodschap.Features.Authentication.Infrastructure.Persistence.Migrations
{
	[DbContext(typeof(AuthenticationDbContext))]
	partial class AuthenticationDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

			modelBuilder.Entity("Boodschap.Features.Authentication.Domain.LocalUser", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<DateTimeOffset>("CreatedUtc")
						.HasColumnType("TEXT");

					b.Property<bool>("IsAdmin")
						.HasColumnType("INTEGER");

					b.Property<string>("NormalizedUsername")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("TEXT");

					b.Property<string>("PasswordHash")
						.IsRequired()
						.HasMaxLength(1024)
						.HasColumnType("TEXT");

					b.Property<string>("Username")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.HasIndex("NormalizedUsername")
						.IsUnique();

					b.ToTable("LocalUsers");
				});
#pragma warning restore 612, 618
		}
	}
}